name: Tic-Tac-Toe CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Install Qt and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          qt6-base-dev \
          qt6-tools-dev \
          libqt6test6 \
          xvfb \
          libgl1-mesa-dev \
          libxkbcommon-x11-0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-xinerama0 \
          libxcb-xfixes0
          
    - name: Create Build Directory
      run: mkdir build
      
    - name: Configure CMake
      working-directory: build
      run: cmake ..
      
    - name: Build
      working-directory: build
      run: cmake --build .
      
    - name: Run Tests with Virtual Display
      working-directory: build
      run: |
        export QT_QPA_PLATFORM=offscreen
        xvfb-run -a ctest --output-on-failure -V
      
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          build/Testing/Temporary/LastTest.log
          build/test_*
        if-no-files-found: ignore

